spring:
  application:
    name: Institution-Management-Services
  data:
    mongodb:
      uri: mongodb://dev-multi-server:27017/institution-management-db

server:
  port: 8762

security:
  sessions: stateless
  